apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Crypto Collector for ${{ values.coin }}
  annotations:
    github.com/project-slug: ${{ parameters.repoUrl | projectSlug }}
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: platform-team
